#!/bin/bash

version1="$1"
version2="$2"

function RunOneComparison()
{
	local subdir="$1"
	local run="$2"

	local file="DQM_V0001_CTPPS_R000$run.root"
	local dir="."

	echo ""
	echo "* $subdir (run $run)"

	./histogram_compare.py -l 0 "$version1/$subdir/$file" "$version2/$subdir/$file"
}

#----------------------------------------------------------------------------------------------------

echo "COMPARING: $version1 vs $version2"

RunOneComparison "reco:2016_preTS2" "275371"
RunOneComparison "reco:2016_postTS2" "283453"
RunOneComparison "reco:2017_preTS2" "301283"
RunOneComparison "reco:2017_postTS2" "305081"
RunOneComparison "reco:2018" "320688"
