#!/bin/bash

version1="$1"
version2="$2"

function RunOneComparison()
{
	local period="$1"
	local run="$2"

	local file="DQM_V0001_CTPPS_R000$run.root"
	local dir="."

	echo ""
	echo "* $period (run $run)"

	local version1_path=$(find $version1 -name $file | head -n 1)
	local version2_path=$(find $version2 -name $file | head -n 1)

#	echo $version1_path
#	echo $version2_path

	./histogram_compare.py -l 0 "$version1_path" "$version2_path"
}

#----------------------------------------------------------------------------------------------------

echo "COMPARING: $version1 vs $version2"

RunOneComparison "2016_preTS2" "275371"
RunOneComparison "2016_postTS2" "283453"
RunOneComparison "2017_preTS2" "301283"
RunOneComparison "2017_postTS2" "305081"
RunOneComparison "2018" "320688"
