#!/bin/bash

periods=(
	"2016_preTS2"
	"2016_postTS2"

	"2017_preTS2"
	"2017_postTS2"

	"2018"
	#"2018A"
	#"2018B"
	#"2018C"
	#"2018D"
)

#----------------------------------------------------------------------------------------------------

function PrintUsage()
{
	echo "USAGE: run_multiple <output dir>"
}

#----------------------------------------------------------------------------------------------------

output_dir="$1"

if [ -z "$output_dir" ]
then
	echo "ERROR: output dir not set"
	PrintUsage
	exit 1
fi

if [ -d "$output_dir" ]
then
	echo "ERROR: directory $output_dir already exists."
	exit 2
fi

echo "* $output_dir"

mkdir -p "$output_dir"

cp "base.py" "$output_dir"
cp "conditions.py" "$output_dir"

for period in ${periods[*]}
do
	cp "${period}_cfg.py" "$output_dir"
done

cd "$output_dir"

for period in ${periods[*]}
do
	cmsRun "${period}_cfg.py" &> "${period}.log" &
	#cmsRun --jobreport "${period}_JobReport.xml" "${period}_cfg.py" &> "${period}.log" &
done
